---

- name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: 'Set smart-gateway objects state={{ state }}'
  k8s:
    state: '{{ state }}'
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.api_exists | default(True)
  loop:
    - name: deployment.yml.j2
    - name: service.yml.j2
    - name: servicemonitor.yml.j2
    - name: configmap.yml.j2
    - name: route.yml.j2
      api_exists: "{{ True if 'route.openshift.io' in api_groups else False }}"
